// angularApp/src/app/app.component.ts
import { Component } from '@angular/core';
import {eventBus} from 'event-bus';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angularApp';

  customEvent = new CustomEvent('customEventName', {
    detail: {
      message: 'Custom event',
      remote: 'AngularApp'
    }
  });
  

  onCustomEvent = () => {
    console.log("Custom event fired");
    window.dispatchEvent(this.customEvent);
  }

  onEventBus = () => {
    eventBus.publish('customEventBusEvent', { message: 'Event Bus', remote: 'AngularApp' });
  }
  
}




<h1>
  Angular App

</h1>
<button (click)="onCustomEvent()">
  custom event
</button>
<button (click)="onEventBus()">
  event bus
</button>

// vue/src/App.vue
<template>
  <div>
    <h1>Vue App</h1>
  </div>
  <button @click="dispatchCustomEvent">custom event</button>
  <button @click="dispatchEventBus">event bus</button>
</template>

<script>
import { eventBus } from 'event-bus';

export default {
  methods: {
    dispatchCustomEvent() {
      const customEvent = new CustomEvent('customEventName', {
        detail: {
          message: 'Custom event from Vue App',
          remote: 'VueApp',
        },
      });
      window.dispatchEvent(customEvent); 
    },
    dispatchEventBus() {
      eventBus.publish('customEventBusEvent', { message: 'Event Bus', remote: 'VueApp' });
    },
  }
};
</script>
<style>

</style>
