// apps/vueApp/src/App.vue
<template>
  <div>
    <h1>Vue App</h1>
  </div>
  <button @click="dispatchCustomEvent">custom event</button>
  <button @click="dispatchEventBus">event bus</button>
  <button @click="saveLocalStorage">storage event</button>
</template>

<script>
import { eventBus } from 'event-bus';

export default {
  methods: {
    dispatchCustomEvent() {
      const customEvent = new CustomEvent('customEventName', {
        detail: {
          message: 'Custom event from Vue App',
          remote: 'VueApp',
        },
      });
      window.dispatchEvent(customEvent); 
    },
    dispatchEventBus() {
      eventBus.publish('customEventBusEvent', { message: 'Event Bus', remote: 'VueApp' });
    },
    saveLocalStorage() {
      localStorage.setItem('storageEvent', JSON.stringify({ message: 'Storage Event', remote: 'VueApp' }));
      window.alert('Storage Event | VueApp');
    }
  }
};
</script>
<style>

</style>

// apps/angularApp/src/app/app.component.ts
import { Component } from '@angular/core';
import {eventBus} from 'event-bus';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angularApp';

  customEvent = new CustomEvent('customEventName', {
    detail: {
      message: 'Custom event',
      remote: 'AngularApp'
    }
  });
  
  onCustomEvent = () => {
    console.log("Custom event fired");
    window.dispatchEvent(this.customEvent);
  }

  onEventBus = () => {
    eventBus.publish('customEventBusEvent', { message: 'Event Bus', remote: 'AngularApp' });
  }
  onStorageEvent = () => {
    localStorage.setItem('storageEvent', JSON.stringify({ message: 'Storage Event', remote: 'AngularApp' }));
    window.alert('Storage Event | AngularApp');
  }
  
}
